name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16.16.0
    - name: install dependencies
      run: yarn
    - name: install packager
      run: yarn global add electron-packager
    - name: install wine
      run: sudo apt-get -y install wine
    - name: build
      run: npm run packager
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r dir.zip out
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: dir.zip
      env:
        GITHUB_TOKEN: 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
