name: Build
on: [push, pull_request]

jobs:
  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16.16.0
    - name: install dependencies
      run: npm install
    - name: install packager
      run: npm install --save-dev electron-packager
    - name: build
      run: npm run packager
    - uses: actions/checkout@v2
    - uses: vimtor/action-zip@v1
      with:
        files: out
        dest: realesea.zip
  goto-realses:
    runs-on: ubuntu-latest
    steps:
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: realesea.zip
        env:
          GITHUB_TOKEN: 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
